server:
  servlet:
    context-path: /api/predictx

# below config is workaround to make swagger run on latest spring boot v2.6.5
# https://github.com/springfox/springfox/issues/3462
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher